# config.yaml

num_epochs: 1000
save_interval: 10
val_interval: 5
patience: 50
batch_size: 4
num_workers: 0

# 數據集路徑（如果未指定，使用預設路徑）
train_image_dir: null
train_mask_dir: null
val_image_dir: null
val_mask_dir: null

# 測試數據集路徑（如果未指定，使用預設路徑）
test_image_dir: null
test_groundtruth_dir: null

# 要載入的模型路徑（如果未指定，使用預設路徑）
model_path: null
